version: 2
updates:
  - package-ecosystem: "maven"
    rebase-strategy: "disabled"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
