name: CI

on:
  pull_request:
    branches:
      - 2.x-pz

jobs:
  build:
    name: Build with JDK ${{ matrix.jdk }}
    strategy:
      matrix:
        jdk:
        - 8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
          cache: 'maven'
      - name: Verify with Maven
        run: ./mvnw -ntp -P run-its verify

